# ===============================
# Application Name
# ===============================
spring.application.name=resumeanalyzer

# ===============================
# Server Port (IMPORTANT FOR RENDER)
# ===============================
server.port=${PORT:8080}

# ===============================
# Active Profile (IMPORTANT)
# ===============================
spring.profiles.active=dev