# ===============================
# Application Name
# ===============================
spring.application.name=resumeanalyzer

# ===============================
# Server Port
# ===============================
server.port=8080

# ===============================
# Active Profile
# ===============================
spring.profiles.active=dev

# ===============================
# Gmail SMTP Configuration
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Your Gmail
spring.mail.username=balajikumar12624@gmail.com

# Google App Password (NO SPACES)
spring.mail.password=rqbpeoiyxurdhvvu

# SMTP Settings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional Timeout Settings
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000